In [2]:
dataset=pd.read_csv('data2.txt',sep='\t',header=None)


In [3]:
dataset.columns=['english','hindi']
dataset['english']=dataset['english'].apply(lambda x:x+' $')
dataset['hindi']=dataset['hindi'].apply(lambda x:'^ '+x+' $')
dataset.head()

english  \
0                          What's he going to say? $   
1      Maybe we should tell him before he sees it. $   
2                                       He saw it. $   
3  How could he see it? I was the first one up; h...   
4                   He was out here when it broke. $   

                                               hindi  
0                        ^ वह क्या कहने जा रहा है? $  
1   ^ शायद हमें उसे देखने से पहले उसे बताना चाहिए। $  
2                                 ^ उसने इसे देखा। $  
3  ^ वह इसे कैसे देख सकता था?मैं पहला था;वह अभी भ...  
4           ^ जब वह टूट गया तो वह यहां से बाहर था। $

In [4]:
X=dataset.english
Y=dataset.hindi

In [5]:
X_words_counts={}
for row in X:
    for words in row.split(' '):
        #print(words)
        X_words_counts[words]=X_words_counts.get(words,0)+1

In [6]:
most_common_X_words = sorted(X_words_counts.items(), key=lambda x: x[1], reverse=True)[:3]
print(most_common_X_words)

[('$', 41), ('to', 20), ('I', 15)]


In [7]:
Y_words_counts={}
for row in Y:
    for words in row.split(' '):
        #print(words)
        Y_words_counts[words]=Y_words_counts.get(words,0)+1

In [8]:
most_common_Y_words = sorted(Y_words_counts.items(), key=lambda x: x[1], reverse=True)[:3]
print(most_common_Y_words)

[('^', 41), ('$', 41), ('नहीं', 15)]


In [9]:
cnt=0
X_WORDS_TO_INDEX={}
for w in X_words_counts:
    X_WORDS_TO_INDEX[w] =cnt
    cnt+=1
X_WORDS_TO_INDEX['#']=len(X_WORDS_TO_INDEX)
ALL_X_WORDS = X_WORDS_TO_INDEX.keys()
print(X_WORDS_TO_INDEX)

{"What's": 0, 'he': 1, 'going': 2, 'to': 3, 'say?': 4, '$': 5, 'Maybe': 6, 'we': 7, 'should': 8, 'tell': 9, 'him': 10, 'before': 11, 'sees': 12, 'it.': 13, 'He': 14, 'saw': 15, 'How': 16, 'could': 17, 'see': 18, 'it?': 19, 'I': 20, 'was': 21, 'the': 22, 'first': 23, 'one': 24, 'up;': 25, 'still': 26, 'in': 27, 'bed.': 28, 'out': 29, 'here': 30, 'when': 31, 'it': 32, 'broke.': 33, 'When?': 34, 'Four': 35, 'o': 36, 'clock': 37, 'this': 38, 'morning.': 39, 'heard': 40, 'a': 41, 'crack': 42, 'and': 43, 'woke': 44, 'up': 45, 'looked': 46, 'out.': 47, 'standing': 48, 'right': 49, 'over': 50, 'there': 51, 'cracked.': 52, 'What': 53, 'doing': 54, 'at': 55, 'four': 56, 'morning?': 57, "don't": 58, 'know.': 59, "He's": 60, 'dreaming': 61, 'of': 62, 'again,': 63, 'walking': 64, 'around.': 65, 'guess': 66, 'is.': 67, "It's": 68, 'getting': 69, 'be': 70, 'just': 71, 'like': 72, 'after': 73, 'died.': 74, 'meaning': 75, 'that?': 76, 'know': 77, 'But': 78, 'thing,': 79, 'Mom,': 80, "you've": 81, 'made

In [10]:
cnt=0
Y_WORDS_TO_INDEX={}
for w in Y_words_counts:
    Y_WORDS_TO_INDEX[w] =cnt
    cnt+=1
Y_WORDS_TO_INDEX['#']=len(Y_WORDS_TO_INDEX)
ALL_Y_WORDS = Y_WORDS_TO_INDEX.keys()
print(Y_WORDS_TO_INDEX)

{'^': 0, 'वह': 1, 'क्या': 2, 'कहने': 3, 'जा': 4, 'रहा': 5, 'है?': 6, '$': 7, 'शायद': 8, 'हमें': 9, 'उसे': 10, 'देखने': 11, 'से': 12, 'पहले': 13, 'बताना': 14, 'चाहिए।': 15, 'उसने': 16, 'इसे': 17, 'देखा।': 18, 'कैसे': 19, 'देख': 20, 'सकता': 21, 'था?मैं': 22, 'पहला': 23, 'था;वह': 24, 'अभी': 25, 'भी': 26, 'बिस्तर': 27, 'में': 28, 'था।': 29, 'जब': 30, 'टूट': 31, 'गया': 32, 'तो': 33, 'यहां': 34, 'बाहर': 35, 'कब?': 36, 'आज': 37, 'सुबह': 38, 'चार': 39, 'ओ': 40, 'घड़ी।मैंने': 41, 'एक': 42, 'दरार': 43, 'सुनी': 44, 'और': 45, 'मैं': 46, 'जाग': 47, 'देखा।जब': 48, 'वहीं': 49, 'खड़ा': 50, 'घड़ी': 51, 'यहाँ': 52, 'कर': 53, 'था?': 54, 'मुझें': 55, 'नहीं': 56, 'पता।': 57, 'फिर': 58, 'उसका': 59, 'सपना': 60, 'है,': 61, 'घूम': 62, 'है।': 63, 'मुझे': 64, 'लगता': 65, 'है': 66, 'कि': 67, 'मरने': 68, 'के': 69, 'बाद': 70, 'ही': 71, 'ऐसा': 72, 'हो': 73, 'है।उस': 74, 'का': 75, 'अर्थ': 76, 'इसका': 77, 'जानता।लेकिन': 78, 'बात': 79, 'पता': 80, 'माँ,': 81, 'आपने': 82, 'पिता': 83, 'साथ': 84, 'भयानक': 85, 'गलती': 86, '

In [11]:
def length_of_sentence(sentence):
    return len(sentence.split(' '))
dataset['e_length']=dataset['english'].apply(length_of_sentence)
dataset['h_length']=dataset['hindi'].apply(length_of_sentence)
Tx=dataset.e_length.max()
Ty=dataset.h_length.max()
print(Tx)
print(Ty)

38
47


In [12]:
def series_to_array(series,vocab):
    X_train=[]
    for row in series:
        r=row.split(' ')
        R=[]
        for a in r:
            R.append(vocab[a])
        X_train.append(R)
    length = max(map(len, X_train))
    y=np.array([xi+[None]*(length-len(xi)) for xi in X_train])
    return y

In [13]:
X_train=series_to_array(dataset.english,X_WORDS_TO_INDEX)
X_train=np.where(X_train==None, len(X_WORDS_TO_INDEX)-1, X_train)
print(X_train)

[[0 1 2 ... 259 259 259]
 [6 7 8 ... 259 259 259]
 [14 15 13 ... 259 259 259]
 ...
 [214 71 239 ... 259 259 259]
 [104 77 240 ... 259 259 259]
 [253 20 254 ... 259 259 259]]


In [14]:
from keras.utils import to_categorical
Xoh = np.array(list(map(lambda x: to_categorical(x, num_classes=len(X_WORDS_TO_INDEX)), X_train)))
print(Xoh.shape)

(41, 38, 260)


In [15]:
Y_train=series_to_array(dataset.hindi,Y_WORDS_TO_INDEX)
Y_train=np.where(Y_train==None, len(Y_WORDS_TO_INDEX)-1, Y_train)
print(Y_train)
Yoh = np.array(list(map(lambda x: to_categorical(x, num_classes=len(Y_WORDS_TO_INDEX)), Y_train)))
Yo=Yoh[:,1:,:]
print(Yo.shape)
ze=np.zeros((1,len(Y_WORDS_TO_INDEX)))
ze[0][Y_WORDS_TO_INDEX['^']]=1
Yo=np.insert(arr=Yo,obj=Ty-1,values=ze,axis=1)
print(Yo.shape)

[[0 1 2 ... 253 253 253]
 [0 8 9 ... 253 253 253]
 [0 16 17 ... 253 253 253]
 ...
 [0 46 217 ... 253 253 253]
 [0 93 94 ... 248 63 7]
 [0 249 246 ... 253 253 253]]
(41, 46, 254)
(41, 47, 254)


In [16]:
n_a=2048
from keras.models import Sequential
from keras.layers import Bidirectional, Concatenate, Permute, Dot, Input, LSTM, Multiply,LSTMCell,RNN,BatchNormalization
from keras.layers import RepeatVector, Dense, Activation, Lambda, Reshape,TimeDistributed,Concatenate
from keras.optimizers import Adam
from keras.utils import to_categorical
from keras.models import load_model, Model
import keras.backend as K
from keras import metrics

In [17]:
encoder_inputs = Input(shape=(Tx, len(X_WORDS_TO_INDEX)))
encoder = Bidirectional(LSTM(n_a, return_state=True))
encoder_outputs, state_h_f, state_c_f,state_h_b,state_c_b = encoder(encoder_inputs)
# We discard `encoder_outputs` and only keep the states.
state_h=Concatenate()([state_h_f,state_h_b])
state_c=Concatenate()([state_c_f,state_c_b])
print(state_h.shape)
encoder_states = [state_h, state_c]

# Set up the decoder, using `encoder_states` as initial state.
decoder_inputs = Input(shape=(None, len(Y_WORDS_TO_INDEX)))
# We set up our decoder to return full output sequences,
# and to return internal states as well. We don't use the 
# return states in the training model, but we will use them in inference.
decoder_lstm = LSTM(2*n_a, return_sequences=True, return_state=True)
decoder_outputs, _, _ = decoder_lstm(decoder_inputs,
                                     initial_state=encoder_states)
decoder_dense = TimeDistributed(Dense(len(Y_WORDS_TO_INDEX), activation='softmax'))
decoder_outputs = decoder_dense(decoder_outputs)
print(decoder_outputs.shape)

# Define the model that will turn
# `encoder_input_data` & `decoder_input_data` into `decoder_target_data`
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

(None, 4096)
(None, None, 254)


In [18]:
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                  ┃ Output Shape              ┃         Param # ┃ Connected to               ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)      │ (None, 38, 260)           │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ bidirectional (Bidirectional) │ [(None, 4096), (None,     │      37,830,656 │ input_layer[0][0]          │
│                               │ 2048), (None, 2048),      │                 │                            │
│                               │ (None, 2048), (None,      │                 │                            │
│                               │ 2048)]                    │                 │                            │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ input_layer_1 (InputLayer)    │ (None, None, 254)         │               0 │ -                          │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate (Concatenate)     │ (None, 4096)              │               0 │ bidirectional[0][1],       │
│                               │                           │                 │ bidirectional[0][3]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ concatenate_1 (Concatenate)   │ (None, 4096)              │               0 │ bidirectional[0][2],       │
│                               │                           │                 │ bidirectional[0][4]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ lstm_1 (LSTM)                 │ [(None, None, 4096),      │      71,286,784 │ input_layer_1[0][0],       │
│                               │ (None, 4096), (None,      │                 │ concatenate[0][0],         │
│                               │ 4096)]                    │                 │ concatenate_1[0][0]        │
├───────────────────────────────┼───────────────────────────┼─────────────────┼────────────────────────────┤
│ time_distributed              │ (None, None, 254)         │       1,040,638 │ lstm_1[0][0]               │
│ (TimeDistributed)             │                           │                 │                            │
└───────────────────────────────┴───────────────────────────┴─────────────────┴────────────────────────────┘

 Total params: 110,158,078 (420.22 MB)

 Trainable params: 110,158,078 (420.22 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
opt = Adam(learning_rate=0.001,beta_1=0.9,beta_2=0.999,decay=0.01)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
model.fit([Xoh,Yoh], Yo, epochs=300, batch_size=64)

D:\Anaconda\Lib\site-packages\keras\src\optimizers\base_optimizer.py:33: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


Epoch 1/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 46s 46s/step - accuracy: 0.0010 - loss: 5.5331
Epoch 2/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.6731 - loss: 3.8604
Epoch 3/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.6731 - loss: 4.7663
Epoch 4/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.6746 - loss: 4.0203
Epoch 5/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 0.0021 - loss: 11.9327
Epoch 6/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.3337 - loss: 7.8092
Epoch 7/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.3363 - loss: 7.5749
Epoch 8/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step - accuracy: 0.3446 - loss: 7.3640
Epoch 9/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 20s 20s/step - accuracy: 0.0794 - loss: 8.3665
Epoch 10/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 0.3653 - loss: 7.5017
Epoch 11/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 0.3653 - loss: 7.3474
Epoch 12/300
1/1 ━━━━━━━━━━━━━━━━━━━━ 18s 18s/step - accuracy: 0.3835 - l

In [ ]:
encoder_model = Model(encoder_inputs, encoder_states)

decoder_state_input_h = Input(shape=(2*n_a,))
decoder_state_input_c = Input(shape=(2*n_a,))
decoder_states_inputs = [decoder_state_input_h, decoder_state_input_c]
decoder_outputs, state_h, state_c = decoder_lstm(
    decoder_inputs, initial_state=decoder_states_inputs)
decoder_states = [state_h, state_c]
decoder_outputs = decoder_dense(decoder_outputs)
decoder_model = Model(
    [decoder_inputs] + decoder_states_inputs,
    [decoder_outputs] + decoder_states)

In [ ]:
INDEX_TO_WORD_Y={y:x for (x,y) in Y_WORDS_TO_INDEX.items()}

In [ ]:
def decode_sequence(input_seq):
    # Encode the input as state vectors.
    states_value = encoder_model.predict(input_seq)

    # Generate empty target sequence of length 1.
    target_seq = np.zeros((1, 1, len(Y_WORDS_TO_INDEX)))
    # Populate the first character of target sequence with the start character.
    target_seq[0, 0, Y_WORDS_TO_INDEX['^']] = 1

    # Sampling loop for a batch of sequences
    # (to simplify, here we assume a batch of size 1).
    stop_condition = False
    decoded_sentence = ''
    while not stop_condition:
        output_tokens, h, c = decoder_model.predict(
            [target_seq] + states_value)

        # Sample a token
        sampled_token_index = np.argmax(output_tokens[0, -1, :])
        sampled_char = INDEX_TO_WORD_Y[sampled_token_index]
        decoded_sentence += sampled_char

        # Exit condition: either hit max length
        # or find stop character.
        if (sampled_char == '$'):
            stop_condition = True

        # Update the target sequence (of length 1).
        target_seq = np.zeros((1, 1, len(Y_WORDS_TO_INDEX)))
        target_seq[0, 0, sampled_token_index] = 1.

        # Update states
        states_value = [h, c]

    return decoded_sentence

In [ ]:
cunt=0
for index, row in dataset.iterrows():
    source=Xoh[index,:,:]
    source=source.reshape(1,Tx,len(X_WORDS_TO_INDEX))
    #print(source)
    result=decode_sequence(source)
    print('##########')
    print("source:", row['english'])
    print('real:',row['hindi'])
    print("output:", result)
    if cunt==10:
        break
    cunt+=1